### ISSUE TITLE
Enhacement: Use Firefox Multi-Account Containers in browser_command

### ISSUE THREAD

**Issue by noizo** [trek10inc/awsume-console-plugin#10]
Hi. Great plugin, use it a lot.
Would be great to be able to provide container name in firefox's [Multi-Account Containers plugin](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)
So the command in
~/.awsume/config.yaml might look like:
```yaml
console:
  browser_command: /Applications/Firefox.app/Contents/MacOS/firefox -container-name "AWS-{profile}" -no-remote "{url}"
```

**Comment by noizo** [comment]
I was able to achieve this by using 
https://github.com/honsiorovskyi/open-url-in-container
Mostly thanks to this comment: https://github.com/mozilla/multi-account-containers/issues/365#issuecomment-526965740

Currently my config looks like:
```yaml
console:
  browser_command: /Users/username/.local/bin/firefox-container --orange --fingerprint --name={profile} "{url}"
```

edit:

glad i could help @albertsj1 , but initially credits are not mine.
And i still think this should be implemented on awsume level, without third parties. cc: @mbarneyjr

**Comment by albertsj1** [comment]
@noizo   Thanks for following up and posting the solution you found.  It's working great for me.
