### ISSUE TITLE
plugin not loaded

### ISSUE THREAD

**Issue by aleksandersumowski** [trek10inc/awsume-console-plugin#2]
I've installed the plugin via `pip3 install awsume-console-plugin` but when issueing `awsume -c` I get `awsume: error: unrecognized arguments: -c`

**Comment by Darwiner** [comment]
> I've installed the plugin via `pip3 install awsume-console-plugin` but when issueing `awsume -c` I get `awsume: error: unrecognized arguments: -c`

I'm doing a blind assumption that you might be on Mac, maybe...

If so, did you install awsume via brew?

I previously did, and the plugin wasn't loading neither.  Uninstalled it and went with a `pip3 install awsume` instead.  Plugin works like a charm now.

**Comment by aleksandersumowski** [comment]
yes, that worked!

It might be helpful to document it somewhere?

**Comment by Darwiner** [comment]
Agreed, would certainly be helpful for future attempts at getting this to work.

Either that and/or also have a way to install this plugin via brew, which, I would guess, would properly link up with the awsume being installed via brew.

**Comment by mgarces** [comment]
I have this issue; I don't want to install awsume via `pip3` so I'm using brew; it seems I can't make `awsume-console-plugin` work properly; is there a workaround?

**Comment by mgarces** [comment]
So, I've found a workaround to have console plugin with homebrew package; I ran `pip3 install awsume-console-plugin` that comes bundled with `awsume` package and now it works fine; 
example: 
``  
/usr/local/Cellar/awsume/4.5.0/libexec/bin/pip3 install awsume-console-plugin
``
Just adjust this to the version installed

**Comment by mbarneyjr** [comment]
Howdy all!

Unfortunately homebrew is not an officially supported install method yet. That was an open source contribution to homebrew core someone made on their own and is not officially maintained by us. The officially recommended way to install awsume is with [pipx](https://pipxproject.github.io/pipx/)

I've added a note to the [awsume's installation documentation](https://awsu.me/general/quickstart.html#installation) to help call that out a little clearer
