### ISSUE TITLE
Merge into awsume

### ISSUE THREAD

**Issue by andymac4182** [trek10inc/awsume-console-plugin#7]
Hi,

With how simple and useful this plugin is, would it be possible to have it merged with the awsume core? It would be a great addition to the core and make the feature a lot more accessible.

Cheers,
Andrew

**Comment by mbarneyjr** [comment]
Thanks for the suggestion!

I think we're interested in keeping it separate for now, but what I did include is an `extras_require` to awsume, so you can do something like this to install it in one go:

```
pip install awsume[console]
```

This should be available as of `awsume==4.5.3`

**Comment by andymac4182** [comment]
Thanks for reviewing :)
